//  Copyright (c) 2024 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// Build Android CTS for Cuttlefish. Only required if testing CTS changes
// or requiring a new revision without updating the CTS on CF jobs.
pipeline {

  agent {
    kubernetes {
      yaml """\
        apiVersion: v1
        kind: Pod
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          labels:
            aaos_pod: "true"
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: android
            effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: aaos_pod
                    operator: Exists
                topologyKey: kubernetes.io/hostname
          hostname: jenkins-aaos-build-pod
          serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
          containers:
          - name: builder
            image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
            imagePullPolicy: IfNotPresent
            command:
            - sleep
            args:
            - 99d
            resources:
              limits:
                cpu: 96000m
                memory: 160000Mi
              requests:
                cpu: 96000m
                memory: 160000Mi
            volumeMounts:
              - mountPath: /aaos-cache
                name: aaos-cache
          volumes:
            - name: aaos-cache
              ephemeral:
                volumeClaimTemplate:
                  spec:
                    storageClassName: ${JENKINS_CACHE_STORAGE_CLASS_NAME}
                    resources:
                      requests:
                        storage: 2000Gi
                    accessModes:
                      - ReadWriteOnce
          nodeSelector:
            workloadLabel: android
      """.stripIndent()
    }
  }

  parameters {
    string(name: 'AAOS_GERRIT_MANIFEST_URL',
           defaultValue: 'https://android.googlesource.com/platform/manifest',
           description: '''Android Mainfest URL, e.g.
           https://android.googlesource.com/platform/manifest''')

    string(name: 'AAOS_REVISION',
           defaultValue: 'android14-qpr1-automotiveos-release',
           description: '''Android revision tag/branch name, e.g:
           android14-qpr1-automotiveos-release
           android-14.0.0_r22''')

    string(name: 'AAOS_LUNCH_TARGET',
           defaultValue: 'aosp_cf_x86_64_auto-userdebug',
           description: '''Build Android CTS for cuttlefish target, e.g.
           aosp_cf_x86_64_auto-userdebug
           aosp_cf_arm64_auto-userdebug''')

    booleanParam(name: 'AAOS_CLEAN_BUILD', defaultValue: false,
                 description: 'Clean the build workspace.')

    string(name: 'AAOS_ARTIFACT_STORAGE_SOLUTION', defaultValue: 'GCS_BUCKET',
           description: '''Android Artifact Storage:
           GCS_BUCKET will store to cloud bucket storage
           Empty will result in nothing stored.''')

    string(name: 'AAOS_ARTIFACT_ROOT_NAME', defaultValue: 'cts_builds',
           description: 'Artifact storage root name')

    // From manual upstream open review change.
    string(name: 'GERRIT_PROJECT', defaultValue: '',
           description: 'Gerrit Project with open review.')
    string(name: 'GERRIT_CHANGE_NUMBER', defaultValue: '',
           description: 'Gerrit review item change number.')
    string(name: 'GERRIT_PATCHSET_NUMBER', defaultValue: '',
           description: 'Gerrit review item patchset number.')
  }

  environment {
    AAOS_CLEAN_BUILD="${AAOS_CLEAN_BUILD == "true" ? 1 : 0}"
  }

  stages {
    stage ('Initialise') {
      when { expression { env.BUILD_NUMBER.toInteger() > 1 } }
      steps {
        container(name: 'builder') {
          sh '''
            AAOS_GERRIT_MANIFEST_URL="${AAOS_GERRIT_MANIFEST_URL}" \
            AAOS_REVISION="${AAOS_REVISION}" \
            AAOS_RPI_REVISION="${AAOS_RPI_REVISION}" \
            AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
            AAOS_CLEAN_BUILD=${AAOS_CLEAN_BUILD} \
            ./workloads/android/pipelines/aaos_builder/aaos_initialise.sh
          '''
        }
      }
    }

    stage ('Build'){
      when { expression { env.BUILD_NUMBER.toInteger() > 1 } }
      steps {
        container(name: 'builder') {
          sh '''
            AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
            AAOS_BUILD_CTS=1 \
            AAOS_CLEAN_BUILD=0 \
            ./workloads/android/pipelines/aaos_builder/aaos_build.sh
          '''
        }
      }
    }

    stage ('Storage'){
      when { expression { env.BUILD_NUMBER.toInteger() > 1 } }
      steps {
        container(name: 'builder') {
          sh '''
            AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
            AAOS_BUILD_CTS=1 \
            AAOS_CLEAN_BUILD=0 \
            AAOS_ARTIFACT_ROOT_NAME="${AAOS_ARTIFACT_ROOT_NAME}" \
            AAOS_ARTIFACT_STORAGE_SOLUTION="${AAOS_ARTIFACT_STORAGE_SOLUTION}" \
            CLOUD_REGION="${CLOUD_REGION}" \
            ./workloads/android/pipelines/aaos_builder/aaos_storage.sh
          '''
        }
      }
    }
  }
}
