apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-writer-sa
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-writer-role
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-writer-rolebinding
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
  - kind: ServiceAccount
    name: keycloak-writer-sa
roleRef:
  kind: Role
  name: keycloak-writer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-cluster-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: keycloak-writer-sa
    namespace: keycloak
---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-post-mtk-connect-job
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-mtk-connect-container
          env:
            - name: PLATFORM_URL
              value: http://keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: https://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
          image: {{ .Values.config.postjobs.keycloakmtkconnect }}
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-post-jenkins-job
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-jenkins-container
          env:
            - name: PLATFORM_URL
              value: http://keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: https://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
          image: {{ .Values.config.postjobs.keycloakjenkins }}
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-post-gerrit-job
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-gerrit-container
          env:
            - name: PLATFORM_URL
              value: http://keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: https://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
            - name: GERRIT_ADMIN_USERNAME
              value: gerrit-admin
          image: {{ .Values.config.postjobs.keycloakgerrit }}
      restartPolicy: Never
